### ISSUE TITLE
what's the purpose of git-sort?

### ISSUE THREAD

**Issue by fanweixiao** [ricardobeat/git-commands#1]
seems it's not work and I can not guess what want to do :sweat_smile:

**Comment by ricardobeat** [comment]
Sorry for the little delay here. It sorts a list of hashes into cronological order:

`git sort xxx yyy zzz` -> yyy xxx zzz in the order they were commited.

If memory doesn't fail me, I used this to sort a list of hotfix patches before applying them to make sure it was reproducible.
